spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    generate-unique-name: false  
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/persadoapi
  jpa:
    generate-ddl: true    properties:      hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
         ddl-auto: update